### ISSUE TITLE
InitializationGroup

### ISSUE THREAD

**Issue by irajs** [haudiobe/DASH-Editing#11]
InitializationGroup | 0 ... N | Specifies a group of Initialization Sets   by a white separated   list of initialization set’s ids of same content type   to indicate that any Period in the Media Presentation has at least one   Adaptation Set that conforms to one of the Initialization Sets referenced in   this element.
-- | -- | --
@id | M | specifies   a unique identifier for this Initialization Group. The attribute shall be a   unique unsigned integer value in the scope of the MPD and shall also be unique   among Initialization Set and Initialization Group ids. |

**Comment by sdp198** [comment]
[Table 3 in 5.3.1.2]
Can I suggest changes to both definitions:
Specifies a white space separated list of ids of Initialization Sets of the same content type.  This indicates that any Period in the Media Presentation has at least one Adaptation Set that conforms to one of the Initialization Sets referenced in this element.

specifies an unsigned integer identifier for this Initialization Group. The attribute shall be unique unique among all Initialization Set and Initialization Group ids in the MPD.

**Comment by haudiobe** [comment]
addressed in version July 30, 2019.
