### ISSUE TITLE
InitializationPresentation

### ISSUE THREAD

**Issue by irajs** [haudiobe/DASH-Editing#12]
InitializationPresentation | 0 ... N | Specifies a group of Initialization Sets   and/or Initialization Groups by a white separated list of initialization set’s ids and Initialization   groups to indicate that create a complete   presentation.   A client supporting all listed   Initialization Sets and Initialization Groups of an Initialization   Presentation is expected to be able to play the entire Media Presentation as   intended by the service provider.
-- | -- | -

  | @id | M | specifies a unique identifier for this Initialization   Presentation. The attribute shall be a unique unsigned integer value in the   scope of the MPD and shall also be unique among Initialization Presentation   ids.
  | @profiles | O | Specifies a URI identifier for this Initialization   Presentation. If present, the scheme shall conform to the Initialization Sets   and Groups listed in this Initialization Presentation.
  | @contentType | O | specifies the content type of initialization Groups   listed in the element.

**Comment by sdp198** [comment]
[Table 3 in 5.3.1.2]

Like in #11 I've got similar changes to suggest:
Specifies a white space separated list of ids of initialization sets and Initialization groups to indicate a combination which creates a complete presentation.  A client supporting all listed Initialization Sets and Initialization Groups of an Initialization Presentation is expected to be able to play the entire Media Presentation as intended by the service provider.

specifies a unique unsigned integer identifier for this Initialization Presentation. The attribute shall be  unique among all Initialization Presentation ids in the MPD.

**Comment by haudiobe** [comment]
implemented in version July 20, 2019
