### ISSUE TITLE
ContentPopularityRateType

### ISSUE THREAD

**Issue by irajs** [haudiobe/DASH-Editing#14]
<xs:element name="ProducerReferenceTime" type="ProducerReferenceTimeType" minOccurs="0" maxOccurs="unbounded"/>
		       <xs:element name=" ContentPopularityRate" type=" ContentPopularityRateType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>

**Comment by haudiobe** [comment]
implemented in version 2019-08-01
