### ISSUE TITLE
5.3.12.1	Initialization Set

### ISSUE THREAD

**Issue by irajs** [haudiobe/DASH-Editing#15]
The semantical definition of Initialization Sets shares all parameters of Adaptation Sets, but an Initialization Set may only include a subset of those parameters. An Adaptation Set referring to an Initialization Set that it conforms to may include additional information, for example: 
-	There may be an Initialization Set with media type audio and a @codecs parameter, but without a @lang attribute. Then each Period includes at least one Adaptation Sets with the same media type, the same @codecs parameter, but each of the Adaptation Sets defines a different language for each Period. This ensures that initialization of an audio playback decoder is possible, but over Period boundaries, the language may change or additional languages may be added. 
-	There may be an Initialization Set with media type video and @maxWidth and @maxHeight parameter and a @codecs parameter. Then at least one Period includes at least one Adaptation Set with the same media type, but its actual codecs parameters and its @maxWidth and @maxHeight may be different than the ones in the Initialization Set, but can be decoded and displayed within the Initialization Set constraints.

An Initialization Set may get assigned a specific profile using the @profiles parameter in order to express conformance to DASH profiles or Interoperability Points.

**Comment by haudiobe** [comment]
Implemented in version 2019-08-01
