### ISSUE TITLE
initializationset@par , ....

### ISSUE THREAD

**Issue by irajs** [haudiobe/DASH-Editing#16]
| @par | O | specifies the picture aspect   ratio of the video media component type, in the form of a string consisting   of two integers separated by ':', e.g.,”16:9”. When this attribute is   present, and the attributes @width and @height for the Representations of Adaptation Sets   conformed to this Initialization Set are also present, the picture aspect   ratio as specified by this attribute shall be the same as indicated by the   values of @width, @height, and @sar, i.e. it shall express the   same ratio as (@width * sarx): (@height * sary), with sarx   the first number in @sar and sary the second number.   If not present, the picture aspect ratio may   be defined for each media component or it may be unknown.
-- | -- | -- | --

Accessibility | 0   … N | specifies   information about accessibility scheme for all Adaptation Sets associated to this   Initialization Set.   For more details, refer to   5.8.1 and 5.8.4.3.
-- | -- | --
Role | 0   … N | specifies information on role   annotation scheme for all Adaptation Sets associated to this   Initialization Set.   For more details, refer to   5.8.1 and 5.8.4.2.
Rating | 0   … N | specifies   information on rating scheme for all Adaptation Sets associated to this Initialization   Set.   For more details, refer to   5.8.1 and 5.8.4.4.
Viewpoint | 0   … N | specifies   information on viewpoint annotation scheme for all Adaptation Sets associated to this   Initialization Set.For more details, refer to 5.8.1 and 5.8.4.5.

**Comment by haudiobe** [comment]
implemented in version 2019-08-01.
