### ISSUE TITLE
Add attribute to BaseURl

### ISSUE THREAD

**Issue by irajs** [haudiobe/DASH-Editing#17]
@timeShiftBufferDepth | O | specifies the   duration of the smallest time shifting buffer for any Representation in the   MPD that is guaranteed to be available for a Media Presentation with type   'dynamic'.    This value replaces   MPD@timeShiftBufferDepth   for the resources that use this BaseURL.   This attribute shall not be set on MPD with   type=’static’[i1]
-- | -- | --

<xs:attribute name="timeShiftBufferDepth" type="xs:duration"/>

**Comment by haudiobe** [comment]
Added as follows


  |   | @timeShiftBufferDepth | O | specifies the duration of the smallest   time shifting buffer for any Representation in the MPD that is guaranteed to   be available for a Media Presentation with type 'dynamic'.    This value overrides MPD@timeShiftBufferDepth for the resources that use this BaseURL.   This value of the attribute is undefined   if the MPD@type attribute is   equal to 'static'.
-- | -- | -- | -- | --
