### ISSUE TITLE
K.2 elements

### ISSUE THREAD

**Issue by irajs** [haudiobe/DASH-Editing#20]
ServiceDescription element shall contain at least one of Latency, PlaybackRate,  OperationQuality  or OperationBandwidth elements.

Latency element shall contain at least one of @target, @max or @min attributes.

and similar

**Comment by haudiobe** [comment]
I am not sure this is necessary, because the element is extensible and we limit this to something now which is unnecessary. I have moved the description to the table, but I am still reluctant to do this change if anyone else shares my concern.

**Comment by haudiobe** [comment]
Not added - technical change
