### ISSUE TITLE
@profiles attribute in InitializationGroup and InitializationPresentation elements

### ISSUE THREAD

**Issue by sdp198** [haudiobe/DASH-Editing#21]
In Table 3 of 5.3.1.2 there are @profiles attributes on the InitializationGroup and InitializationPresentation elements, but the definitions don't seem to make sense.

The current text is:
"Specifies a URL identifies for this Initialization Group.  If present the scheme shall conform to the Initialization Sets listed in this Initialization Group."

Is it the same profile as used in MPD@profiles?  I assume it is from the schema fragment.  If so it might be better to say something along the lines of what is in Table 13 of 5.3.7.2 for Common AS and Rep properties, eg:
"specifies the profiles which the listed Initialization Groups conform to.  The value shall be a subset of the value in the MPD@profiles attribute.
If not present the value is inferred to be the same as the MPD@profiles attribute.
The same syntax is used as defined for the MPD@profiles attribute."

**Comment by haudiobe** [comment]
implemented July 30, 2019.
