### ISSUE TITLE
Main Adaptation Set term in Preselections

### ISSUE THREAD

**Issue by sdp198** [haudiobe/DASH-Editing#22]
In the new Preselections text (5.3.11.1) the term Main Adaptation Set is introduced.  I'm a bit worried about the term, because I'd normally use that in conversation (clearly I have fun chats with my colleagues) to mean "The Adaptation Set with Role=main".

Is it too late to change this?  Assuming it is, it might be worth making clear that Main in this context is unrelated to the role.

**Comment by haudiobe** [comment]
Added a note during editing on Jul 30

Note: In the context of Preselection the term "Main Adaptation Set" is used. Note that this term is not to be confused with an Adaptation Set that has assigned the main Role.
