### ISSUE TITLE
Preselection ordering text in 5.3.11.5.2

### ISSUE THREAD

**Issue by sdp198** [haudiobe/DASH-Editing#23]
I'm struggling to understand the text in sections 5.3.11.5.2 and 5.3.11.5.3.  I'll try to suggest and alernative tomorrow morning.

**Comment by sdp198** [comment]
I suggest changing the text to the version below.

Note that 5.3.11.5.3 can't inherit from 5.3.11.5.2, as otherwise the representations would have to work with the harder conformance requirements.

**5.3.11.5.1	Conformance rules for Tracks in Unordered Preselections**
Where multiple Adaptation Sets indicate this type of ordering, each Adaptation Set and the contained Representations follow the regular conformance rules for multi-segment tracks as defined in subclause 5.3.5.1.

No additional conformance rules are defined for the combination of Representations in different Adaptation Sets within Preselections. 

**5.3.11.5.2	Conformance rules for Tracks in Time-Ordered Preselections**
Where multiple Adaptation Sets indicate this type of ordering, each Adaptation Set and the contained Representations follow the conformance rules for multi-segment tracks as defined in subclause 5.3.11.5.1. 

In addition, the concatenation of the following shall represent a conforming Segment track as defined in subclause 4.5.4 and conforming to the media type as specified in the @mimeType attribute for the Representation of the Main Adaptation Set:

- An Initialization Segment of one Representation of the Main Adaptation Set (specified by the first id in the @preselectionComponents  attribute or the Preselection Descriptor)
- media segments/subsegments of one Representation from each Adaptation Set referenced in the Preselection ordered by non-decreasing first decode times.

Note: This does not constrain the order of segments with the same first decode time.

If Adaptation Sets within a Preselection are time-ordered as defined in this sub clause, they should share the same value for the @segmentAlignment or @subsegmentAlignment attributes, i.e. the Representations of all Adaptation Sets referenced by the Preselection are segment/subsegment aligned.

**5.3.11.5.3	Conformance rules for Tracks in Fully-Ordered Preselections**
Where multiple Adaptation Sets indicate this type of ordering, each Adaptation Set and the contained Representations follow the conformance rules for multi-segment tracks as defined in subclause 5.3.11.5.1. 

In addition, the concatenation of the following shall represent a conforming Segment track as defined in subclause 4.5.4 and conforming to the media type as specified in the @mimeType attribute for the Representation of the Main Adaptation Set:
- An Initialization Segment of one Representation of the Main Adaptation Set (specified by the first id in the @preselectionComponents  attribute or the Preselection Descriptor)
- media segments/subsegments of one Representation from each Adaptation Set referenced in the Preselection ordered first by non-decreasing first decode times and then by position in the list given in @preselectionComponents.
 
If Adaptation Sets referenced by a Preselection are fully ordered as defined in this sub clause, they shall share the same value for the @segmentAlignment or @subsegmentAlignment attributes, i.e. the Representations of all Adaptation Sets referenced by the Preselection shall be segment/subsegment aligned.

**Comment by haudiobe** [comment]
implementend in 2019-08-01
