### ISSUE TITLE
Change to definition of MPD@profiles

### ISSUE THREAD

**Issue by sdp198** [haudiobe/DASH-Editing#24]
In 8.1 new text "The identifier of a profile shall not contain any comma" has been added.

I understand the problem with commas since the profiles string contains a comma delimited list, but this change rules out tag: URNs.

Given the subsequent text recommends including a date where URLs are used as profiles, it would seem that tag URNs are actually a good choice for identifiers based on domain names.  Do we know that no-one is doing this before making a change that prevents the use of them?

**Comment by haudiobe** [comment]
We will not implement this, it was a technical decision
