### ISSUE TITLE
service description

### ISSUE THREAD

**Issue by irajs** [haudiobe/DASH-Editing#9]
change semantics to:

specifies the service description that is intended by the service provider on how the service is expected to be consumed. 
It shall provide a valid service description as described by Annex K.3 and Annex K4.
For details refer to Annex K.

**Comment by sdp198** [comment]
Can I suggest changing the first paragraph too?

I think it should become:
specifies the service description detailing how the service provider expects the service to be consumed.

**Comment by sdp198** [comment]
[And this is Table 3 in section 5.3.1.2]

**Comment by haudiobe** [comment]
Implement in version Jul 30, 2019
